<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class QuestionBank extends Model
{
    protected $fillable = [
        'category_id',
        'sub_category_id',
        'kode_soal',
        'type',
        'question_text',
        'question_image',
        'options',
        'correct_answer',
        'difficulty',
        'score_correct',
        'score_incorrect',
        'explanation'
    ];

    protected $casts = [
        'options' => 'array',
        'correct_answer' => 'array',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function subCategory()
    {
        return $this->belongsTo(SubCategory::class);
    }

    public function getQuestionImageAttribute($value)
    {
        return $value ? str_replace('\\', '/', $value) : $value;
    }

    public function getQuestionTextAttribute($value)
    {
        if (!$value) return $value;
        $appUrl = rtrim(url('/'), '/');
        // Handle variations of relative paths generated by TinyMCE like src="../../storage/" or src="/storage/"
        return preg_replace('/src="(?:\.\.\/)*\/?storage\//', 'src="' . $appUrl . '/storage/', $value);
    }

    public function getExplanationAttribute($value)
    {
        if (!$value) return $value;
        $appUrl = rtrim(url('/'), '/');
        return preg_replace('/src="(?:\.\.\/)*\/?storage\//', 'src="' . $appUrl . '/storage/', $value);
    }
}
